<!doctype html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html"; charset=UTF-8">
        <title>EasyWika</title>
        <link rel="stylesheet" type="text/css" href="css/global.css">
        <link rel="stylesheet" type="text/css" href="css/search.css">
    </head>
    <body>
        <div id="form-signin">
            <div>
                <h1>EasyWika</h1>
            </div>
            <form method="post">
                <input type="text" name="pattern" placeholder="Suchwort" required="required" />
                <button type="submit">
                    suchen
                </button>
            </form>
        </div>
    </body>
</html>